spring:
  cloud:
    stream:
      function:
        definition: userConsume, processNdc
      bindings:
        userConsume-in-0:
          destination: Blah.Topic
        processNdc-in-0:
          destination: Blah.Topic
      kafka.streams:
        binder:
          functions:
            userConsume:
              applicationId: user-consume-app-id
            processNdc:
              applicationId: process-user
          deserialization-exception-handler: logandcontinue
          auto-add-partitions: true
          min-partition-count: 3
          configuration:
            num.stream.threads: 3
            spring.json.trusted.packages: '*'
          consumer-properties:
            max.poll.records: 500
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer